#!/bin/sh 

NODE_OPTIONS="--max-old-space-size=4096" 

if [ $# = 2 ] && [ $1 = "--max-heap" ] && [ $2 -ge 1024 ]
then
    NODE_OPTIONS="--max-old-space-size="$2 
fi


node $(npm root -g dexcalibur)/dexcalibur/dexcalibur.js $@

